exports.fullLoadingScreen = document.getElementById('screen-loading');
exports.fullLoginScreen = document.getElementById('screen-login');
exports.fullCuppingScreen = document.getElementById('screen-cupping');
exports.loginEmail = document.getElementById('loginEmail');
exports.loginPassword = document.getElementById('loginPassword');
exports.loginSubmit = document.getElementById('loginSubmit');
exports.screens = document.querySelectorAll('.screen');
exports.welcomeName = document.querySelector('.cupping-welcome .name');
exports.cuppingsList = document.getElementById('cuppings-list');
exports.cuppingForm = document.getElementById('screen-cupping-form');
exports.selectTypeList = document.getElementById('select-type');
exports.cuppingFormSliders = document.getElementById('cupping-form-sliders')
exports.formSubmit = document.getElementById('formSubmit')